Pin the version of nixpkgs
With a freshly-installed nix I ran into this issue:

    ; nix-shell
    error: Package ‘python-2.7.18.6-env’ in /nix/store/arj2cbiypb90whh8ai3m68q49dijy688-nixpkgs/nixpkgs/pkgs/development/interpreters/python/cpython/2.7/default.nix:330 is marked as insecure, refusing to evaluate.
    ...

Following the instructions (of allowing insecure packages) I ended up
with the next issue:

    ; nix-shell

    ...

    error: attribute 'wxPython' missing

           at /home/bheesham/dev/notes-app/shell.nix:4:5:

                3|     ps.whoosh
                4|     ps.wxPython
                 |     ^
                5| ])).env
    (use '--show-trace' to show detailed location information)

This commit pins a version of nixpkgs where:

* the Python version is 2.7.17;
* wxPython is available; and
* we don't need to allow insecure packages (though this benefit is
  debatable).